### ISSUE TITLE
It works in 2020.1

### ISSUE THREAD

**Issue by geslotencirkel** [karasusan/OpenVDBForUnity#21]
Had to do some VDB work and checked this out - after sometime and seeing the issues here I figured i'd share how you can get it to work:

follow instructions upto the "Packages->OpenVDB->Download Library" - this is the broken part potentially on everyones Windows installs.

When upgrading the project, clean it up, otherwise Unity doesn't correctly resolve the UnityEngine methods for EXR conversion - I had to nuke the Library and all of the other nonessential folders.

To get the latest available plugin, you will need to download and place it manually - depending on your OS, you will find the download URLs in LibraryDownloader.cs - for win64bit its here 
`https://dl.bintray.com/kazuki/conan/kazuki/OpenVDBNativePlugin/0.0.1/stable/0/package/2c0ede688cb6609cf77dafa57a7200b861971804/0/conan_package.tgz`

Open this with 7zip and get the openvdbi.dll and place it into
`Assets\OpenVDB\Scripts\Plugins` and restart the project.

You should be able to reimport the .vdbs included with the project as stated in the instructions.

**Comment by MattTree** [comment]
Good tips. I'm stuck on:

> Library\PackageCache\com.unity.render-pipelines.high-definition@8.2.0\Runtime\Utilities\HDTextureUtilities.cs(17,33): error CS1061: 'Texture2D' does not contain a definition for 'EncodeToEXR' and no accessible extension method 'EncodeToEXR' accepting a first argument of type 'Texture2D' could be found (are you missing a using directive or an assembly reference?)

I tried deleting the file (my interpretation of your "nuke" term), but Unity rebuilt it.

I looked up [the documentation](https://docs.unity3d.com/ScriptReference/ImageConversion.EncodeToEXR.html) to find a potentially missing 'using directive', but the documentation's code matches the code in this file.

I will add any other clues I find.

**Comment by geslotencirkel** [comment]
I'm not sure why that happens exactly but removing Library, ProjectSettings and UserSettings directories from the project folder before starting it up will make Unity regenerate the configs and fix issues like that. Sometimes you also have to remove and re-add the packages  - i think for this Texture2D error you have to remove the HDRP package sometimes.

Healing downloaded projects is something you gotta do especially if you use diifferent versions of Unity than the one that the project was first created in.

**Comment by MattTree** [comment]
It worked. The key was deleting ProjectSettings and UserSettings to prevent the outdated Library folder from being generated.

This got me to a new but easy error which required me to install Unity's post processing package.

Side note / heads up: The VDB rendered objects in 2020.1 seem to clip / disappear early. In 2018.2 you can fly your camera all the way through the cloud without any clipping / disappearance.

2020.1 reference image:
![image](https://user-images.githubusercontent.com/68766223/91166390-eaaedd00-e697-11ea-8fbc-2cae423ca593.png)

As you get closer in 2020.1 (disapparance):
![image](https://user-images.githubusercontent.com/68766223/91166401-f00c2780-e697-11ea-8407-fe6e8ee49671.png)

2018.2 reference image:
![image](https://user-images.githubusercontent.com/68766223/91166508-18942180-e698-11ea-8b9c-6727e97b5028.png)

As you get closer in 2018.2 (no disappearance):
![image](https://user-images.githubusercontent.com/68766223/91166548-25187a00-e698-11ea-993b-60f578034022.png)

The same is true for other VDB objects.

**Comment by MattTree** [comment]
If I comment out ENABLE_TRACE_DISTANCE_LIMITED in VolumeStandard.shader, the cloud stops disappearing up close, but now the background turns black when you get close. Below is an animation of the camera flying straight through the cloud:

![image](https://user-images.githubusercontent.com/68766223/91167413-8ab93600-e699-11ea-8b15-61ee393af348.png)
![image](https://user-images.githubusercontent.com/68766223/91167440-9573cb00-e699-11ea-8c37-2444d7486e8b.png)
![image](https://user-images.githubusercontent.com/68766223/91167453-9a387f00-e699-11ea-9170-46354ab136c9.png)
![image](https://user-images.githubusercontent.com/68766223/91167462-9efd3300-e699-11ea-92b6-1e4dcd58b2d0.png)
![image](https://user-images.githubusercontent.com/68766223/91167477-a58baa80-e699-11ea-85ce-5e5438aaf70d.png)

Another clue: If I turn the sun intensity up from 10 thousand to 10 million, the background shows (but now the sun is at 10 million).

![image](https://user-images.githubusercontent.com/68766223/91170122-0321f600-e69e-11ea-9ec2-b710f7796871.png)
![image](https://user-images.githubusercontent.com/68766223/91170148-0917d700-e69e-11ea-9776-4ec51b077d91.png)

(Added a cube and another cloud)

Note that the brown ground has become gray due to the super bright sun.

------------

# Edit

The background turning black might be a 2020.1 HDRP thing in general. I found this effect with Visual Effect Graph particle systems, too:

Reference image:
![image](https://user-images.githubusercontent.com/68766223/91241523-b58fa280-e70a-11ea-9024-ed47a6d6e6a8.png)

Background disappears (darkens):
![image](https://user-images.githubusercontent.com/68766223/91241553-c809dc00-e70a-11ea-9072-c958c5d7d31b.png)

Background appears if I turn the sun up to 10 million:
![image](https://user-images.githubusercontent.com/68766223/91241582-dbb54280-e70a-11ea-847b-954448a912cb.png)

**Comment by lizelive** [comment]
@geslotencirkel could you make a pr?

**Comment by FCgames** [comment]
hello can someone send me the unity package? I can not find it.

**Comment by lejeanf** [comment]
Does anyone know how to use animated VDBs? I tried to make a C# script to activate/deactivate them in sequence but of course it is way too slow. Works well with 10 but over that it's not usable...

**Comment by ohiro26** [comment]
> 
> 
> Had to do some VDB work and checked this out - after sometime and seeing the issues here I figured i'd share how you can get it to work:
> 
> follow instructions upto the "Packages->OpenVDB->Download Library" - this is the broken part potentially on everyones Windows installs.
> 
> When upgrading the project, clean it up, otherwise Unity doesn't correctly resolve the UnityEngine methods for EXR conversion - I had to nuke the Library and all of the other nonessential folders.
> 
> To get the latest available plugin, you will need to download and place it manually - depending on your OS, you will find the download URLs in LibraryDownloader.cs - for win64bit its here
> `https://dl.bintray.com/kazuki/conan/kazuki/OpenVDBNativePlugin/0.0.1/stable/0/package/2c0ede688cb6609cf77dafa57a7200b861971804/0/conan_package.tgz`
> 
> Open this with 7zip and get the openvdbi.dll and place it into
> `Assets\OpenVDB\Scripts\Plugins` and restart the project.
> 
> You should be able to reimport the .vdbs included with the project as stated in the instructions.

Can somebody upload the dll again please? The link is broken.
Thank you.

**Comment by JacobVan3D** [comment]
@MattTree @geslotencirkel @lizelive 
Would it be possible for one of you to upload the package again? Bintray seems to be down.

**Comment by supuo** [comment]
@MattTree 

I found that the reason of it is Unity uses camera relative rendering in HDRP. The GetCameraPosition returns an absolute world space pos, but space transition matrices all use relative world space. So IsInnerCube will return a wrong value and the cloud disappears as you get closer to the cube.

So GetCamerPosition should be
```
inline float3 GetCameraPosition() {
  #if (SHADEROPTIONS_CAMERA_RELATIVE_RENDERING != 0)
  return 0;
  #else
  return _WorldSpaceCameraPos;
  #endif
}
```

Another thing is that the nearCameraPos should be `float3 nearCameraPos = cameraPos + GetCameraNearClip() * cameraDir / dot(cameraDir, GetCameraForward())`. Otherwise, you can't get a near clip plane but a near clip sphere.

My Unity version is 2022.3.
